### ISSUE TITLE
预习任务-前端：JavaScript

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#1]
[官方教程链接](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript)
我们重点关注JS的基础语法。
请大家及时汇报学习情况，尽快完成。
@CapFreddy @17373432 @Jiyuan-Yang

**Comment by Jiyuan-Yang** [comment]
# 进度汇报-0408
## 完成学习以下部分：
- JavaScript 第一步
- JavaScript 基础要件
- JavaScript 对象
## 正在学习：
- JavaScript API

**Comment by 17373432** [comment]
陈驰-进度汇报-0408
## 完成学习以下部分：

- JavaScript 第一步
- JavaScript 基础要件

## 正在学习：

- JavaScript 对象

**Comment by 17373432** [comment]
陈驰-进度汇报
## 完成学习以下部分：

- JavaScript 对象

## 遇到的问题及解决方法：

1. 为"弹球"示例添加新功能中恶魔环没有显示在网页上

   构造器中的为属性赋值要加`this`。

2. 为"弹球"示例添加新功能中恶魔环无法移动

   官方给的恶魔环的`setControls()`方法不全，将`e.key`右边的条件判断改成`'ArrowLeft'`、`'ArrowRight'`、`'ArrowUp'`、`'ArrowDown'`。

**Comment by Jiyuan-Yang** [comment]
杨继远-进度汇报
## 完成学习以下部分
- 学习了Asynchronous JavaScript，了解了JS的异步机制以及相关的`Async callbacks`和`promise`，同时学习了常用的`setTimeout`和`setInterval`。
- 据此学了一下[Axios](https://www.kancloud.cn/yunye/axios/234845/)，其利用了`promise`，为我们的项目在JS脚本中向服务端发出Request的主要工具。

**Comment by linfeng-du** [comment]
杜林峰-进度汇报
### 已完成
#### JavaScript第一步
- HTML - CSS - JavaScript三层次：结构化，样式定义，动态控制。
- 网页加载：HTML和CSS组装网页，在此基础上，JavaScript代码通过just-in-time compiling技术在标签页所形成的独立环境中解释执行。由内建于web浏览器的Document Object Model API实现对HTML和CSS的动态控制。
- 编程控制JavaScript在HTML加载完毕后执行：外部引用时使用`async`或在`<script>`段监听`DOMContentLoaded`事件。

##### 疑问
Server - Client：客户端代码是否由服务器端产生？服务器端的代码是否即为前后端交接的部分？

#### JavaScript基础要件
- 通过事件刻画HTML页面的变化。

#### JavaScript对象介绍
- prototype机制与继承的异同。
- 数据传输格式：JSON。

### 下一步
Asynchronous JavaScript & 客户端网页API。

**Comment by Jiyuan-Yang** [comment]
任务完成。
