### ISSUE TITLE
功能体验-综合

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#12]
现在已经完成了对project创建的bug的修复，基本上的功能已经可以使用了。现在github上的是没有`app/config/production_constant.rb`、`app/config/development_constant.rb`以及`db/development.sqlit3`的，这几个我们彼此不一样，直接ignore，请注意。

如果出现无法使用的情况，尝试清空浏览器缓存、cookie。

在接下来push自己的代码时也请注意，第一次push时，**一定**要使用`git rm -r --cached .`清空本地缓存，不要把咱们不一样的那几个文件push上来。

咱们接下来的一段时间需要不断体验各种功能，了解其实现，并提出修改意见。请大家部署好环境，抓紧时间体验，然后将自己的建议等放到本issue下。

**Comment by Jiyuan-Yang** [comment]
前端-0410
- 可以调整一下配色
- 可以在导航栏上增加更多内容
- 可以丰富页面展示信息
- 可以在编辑和输入窗口增加一些快捷键

**Comment by Kennnnnnji** [comment]
### TODO-0410
#### 前端 & 后端
- 在平台页面上添加退出登录按钮，实现用户切换的功能

**Comment by 804035184** [comment]
## 教师身份登陆：（404可能是我配置的问题？）

编辑班级 404

点击跳转到gitlab 404

在班级中添加个人项目和结对项目都会返回班级列表，正常应该返回项目列表

在班级中添加个人项目和结对项目，但最终所有的都在结对项目里面,如果该班级没有结对项目，新建的个人项目就没有显示

结对项目和个人项目的编辑404

点击创建好的项目404

点击自动测试报错（可能是我配置的问题？）

创建团队时间里面的那个团队事件说明打不开0.0

创建团队事件后显示了团队事件列表，但是返回后还是创建页面

点击左上角的Gitlab会报500

## 学生身分登陆：

刚登陆弹出来一个写着“没有结果”的框 然后自动消失了，在打开空的栏目也是这样

### 项目看板：

新建问题中设置的优先级会消失，并且在查看的时候设置优先级也是无效的

项目看板的条目中有一个Administrator/xxx，并不是班级的

处理中的问题原本是doing 但close再reopen后会变成to do

项目看板的计数每次进入都清零，并没有和下面的一致

权重无法设置，无论是新建还是后面更改都会变成无

问题中的链接那一栏新建的时候并不能设置，点击进去是404

问题的标签一栏最开始尝试是无数据，不知为什么在之后又出现了todo和doing，但是查看项目的时候标签栏一直是空的，里面的选项也都是无数据

新建标签为doing的却也在待处理列中

并没有找到问题的删除按钮

### 冲刺：

点击新建冲刺会404

### 问题：

问题界面也有Administrator/xxx

同样无法编辑和项目看板类似的权重优先级标签链接

### Gitlab： 

还是跳转到404



还不清楚怎么增加用户来测试增加删除人员的功能

**Comment by 804035184** [comment]
我的项目体验物语果然有问题（续）————大闸蟹的项目再体验

（配环境真是太神奇了，再次感谢各位老哥的帮助

大闸蟹 继续昨天的工作，将bug和完善分开，有些我认为既是bug又是改进的说了两遍，还是建议都看一下

# 教师身份登陆：

## BUG：

### 1.个人项目和结对项目混淆

在班级中添加个人项目和结对项目，但最终所有的都在结对项目里面,如果该班级没有结对项目，新建的个人项目就没有显示

### 2.团队事件说明打不开

创建团队时间里面的那个团队事件说明打不开

### 3.团队项目列表一直是空的

团队项目列表界面意义不明，没有创建按钮

## 改进之处：

### 1.编辑班级和项目

目前编辑班级会跳转到gitlab，在gitlab却并没有能够跳转回平台的功能只能按返回，并且在gitlab修改后返回后只能返回到gitlab的修改前界面，在修改前界面再次点击返回才能回到平台，并且此时返回的平台是数据更新之前的。项目的编辑存在类似的问题。

改进建议：封装编辑功能，增加编辑后返回界面的功能并自动刷新

### 2.创建项目

在班级中添加个人项目和结对项目都会返回班级列表

改进建议：返回项目列表并自动刷新

### 3.建议添加删除项目的功能

目前删除项目只能到gitlab的设置-高级设置里面去操作，平台并不提供删除功能

### 4.优化重名的报错

目前重名报错是rails报错那样跳转到一个新界面，建议增加一个判断是否存在的功能，弹出提示框

### 5.返回功能

目前想要回退只能点击返回建，创建项目之后点击返回建又会进到创建界面

建议改进逻辑增加返回按钮或菜单栏

# 学生身份登陆：

## BUG：

### 1.属性失效：

优先级、权重设置都是无效的，标签栏只有无数据

在使用过to do，或者doing的问题项目过后，新建项目中的标签会出现doing和todo的标签，但是设置后依旧在问题查看上是空的

### 2.项目看板计数

项目看板进入后计数会全部清零，在本界面新建会从0开始增长，逻辑混乱

### 3.问题close reopen后都会变成todo

问题关闭再打开后不会恢复到原本的状态，都是todo，并且在项目看板中，原本拖到doing中的close再reopen后会使得doing的列中出现todo的问题，刷新后才会正常

### 4.在项目看板中新建项目都会默认加到todo列

（关于新建时增加标签的问题见1）新建doing标签也会默认显示在todo，刷新后恢复正常

### 5.新建的时候甚至可以选两个标签，又是todo又是doing

（关于新建时增加标签的问题见1），新建时可以同时选择两个标签，最终结果是doing，查看的标签列依旧是空的，位置也默认在了todo

### 6.冲刺

点击新建冲刺会选择项目名称，但没有区分班级，不同班级中的相同名字的项目无法区分

### 7.查看建立的冲刺中有看板选项，意义不明

我理解是对应的项目的看板，但却跳转到了一个意义不明的空的看板

### 8.冲刺没有显示是哪个班级哪个项目，不同班级项目的同名冲刺无法区分，并且冲刺没有跳转到gitlab的选项，在平台中永远无法区分

### 9.冲刺详情里面的燃尽图看起来是因为拉取到了空的看板所以是空的

### 10.冲刺建立的时候若没有设置起始和截至时间，在查看冲刺详情的时候会让添加开始日期和截止日期，但是每次点击开始日期和截止日期配置都会出现服务器错误的报错，并且也没有确定修改的选项

### 11.冲刺有close和reopen按钮，但是意义不明

### 12.学生在班级的团队项目栏中点击创建团队项目会报错

### 13.在班级博客中点击新建博客，创建完后一直加载中转圈，新建Daily Scrum也是一样的情况

## 改进

### 1.问题分区错误

在查看一个项目的问题的界面点击新建问题，然后选择新建其他项目的问题，这个问题会被归到正在查看的项目中，全部都刷新一边会恢复正常

建议修改显示和刷新的逻辑

### 2.问题没有删除功能

只能进入gitlab删除，且返回只能通过返回键，并且首先会返回到刚刚删除的界面上提示404，很不友好

建议增加删除功能并封装

### 3.Administrator 与班级混杂在一起 意义不明

### 4.问题close reopen后都会变成todo

问题关闭再打开后不会恢复到原本的状态，都是todo，并且在项目看板中，原本拖到doing中的close再reopen后会使得doing的列中出现todo的问题，刷新后才会正常

### 5.在项目看板中新建项目都会默认加到todo列

（关于新建时增加标签的问题见1）新建doing标签也会默认显示在todo，刷新后恢复正常

### 6.新建的冲刺需要刷新才能看见

### 7.查看建立的冲刺中有看板选项，意义不明

我理解是对应的项目的看板，但却跳转到了一个意义不明的空的看板

### 8.冲刺没有显示是哪个班级哪个项目，不同班级项目的同名冲刺无法区分，并且冲刺没有跳转到gitlab的选项，在平台中永远无法区分

### 9.冲刺详情里面的燃尽图看起来是因为拉取到了空的看板所以是空的

### 10.冲刺有close和reopen按钮，但是意义不明

### 11.在班级博客中点击新建博客，创建完后一直加载中转圈

# 广播测试：（根本找不到BUG，老杨NB

### 1.建议弄一个标签表示已读未读，点击已读直接删除....，错误点一下全部已读没有确认之类的提示直接都没了有点吓人

### 2.空的广播建议不让发

# 多用户测试：

### 1.老师和学生点击加入班级报错

### 2.不同老师甚至可以建相同名字的班级2333然后所有班级里面就出现了两个重名的班级

### 3.老师添加学生的界面没有返回按钮

### 4.被加到班级里的学生确实能访问班级，但是项目看板和冲刺并访问不到班级！！！



关于自动测试的一点问题：

自动测试怎么个测试法，目前学生访问到的项目就是项目本身的仓库，目前来看大家都往这个仓库里面传更简单？但可能需要文件名规定或者分支或者tag之类的标明身份

**Comment by Jiyuan-Yang** [comment]
已进行bug和功能拆解，并提交issue。
