### ISSUE TITLE
【0413】完善组：增加注销功能

### ISSUE THREAD

**Issue by Kennnnnnji** [Jiyuan-Yang/teach#16]
## 添加注销功能
在平台页面上添加退出登录按钮，实现用户切换的功能

**Comment by Kennnnnnji** [comment]
## 后端
设置好了整体的流程包括routes和controller的函数，但是暂时无法实现gitlab的log out操作。参考[GitLab issue](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/40984)，现在GitLab的oauth2没有log out api。
- [ ] 替代方案：访问log out地址（ http://localhost:30000/users/sign_out ），然而出现404错误。
- [x] 替代方案2：通过引导用户进入Git Lab界面进行注销

**Comment by Kennnnnnji** [comment]
## UI设计
![G7Ifhj.png](https://s1.ax1x.com/2020/04/11/G7Ifhj.png)

**Comment by Kennnnnnji** [comment]
## 后端代码更新 Change Log 2020-4-11 14:22
### Commit
[add LOGOUT - v1 -backend](https://github.com/Jiyuan-Yang/teach/commit/c32e5385f13ffbd32abb74b173f2501bd1c59680)
### 描述
增加Log out 接口
```
get '/logout', to: 'sessions#logout'
```
以及配套代码
### 涉及文件
1. app/controllers/sessions_controller.rb
2. lib/gitlab_api.rb
3. config/routes.rb

**Comment by Kennnnnnji** [comment]
## 后端：逻辑更改 Change Log 2020-4-12 21:51
commit：[add LOGOUT v2 -backend](https://github.com/Jiyuan-Yang/teach/commit/20b355f96277c8e5afa38cf22e3ea6dd1a2177c9)
更新了注销的逻辑，现在是一次点击“注销平台”按钮之后完成平台注销并跳转到GitLab，然后用户在GitLab上自行Sign out

## 前端：UI修改
使用一个按钮“注销平台”完成操作 @CapFreddy

**Comment by linfeng-du** [comment]
## 前端：添加“注销平台”按钮
### commit
[add LOGOUT v2 -frontend](https://github.com/Jiyuan-Yang/teach/tree/2b0dd2862b4887df4039748d2f73232b4b7da495)
### 涉及文件
app/javascript/src/shared/components/
- navbar.vue
- teacher_navbar.vue
### 更新
- 学生页面和教师页面添加“注销平台”按钮
- 新按钮触发后与“GitLab”按钮返回相同的GitLab页面，但实际是前往“/logout”

**Comment by Jiyuan-Yang** [comment]
已完成
