### ISSUE TITLE
预习任务-前端：Vue.js

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#2]
[官方中文文档](https://cn.vuejs.org/v2/guide/)
我们重点关注“基础”一节。
请大家及时汇报学习情况，尽快完成。
@CapFreddy @17373432 @Jiyuan-Yang

**Comment by Jiyuan-Yang** [comment]
杨继远-进度汇报
已完成基础部分学习。

**Comment by Jiyuan-Yang** [comment]
杨继远-进度汇报
- 根据刚才学习的JS中异步刷新以及Axios的使用，重新复习了Vue中计算属性（computed）与方法（method）的区别，同时理解了之前不太清楚的watch及其实例。
- 学习的template中的prop字段以及独立的组件（`*.vue`）的工作流程。
- 根据项目代码，查找了：
  - `$` 表示实例，即`this.$el`表示`el`所对应的DOM中的实例。同时代码中其他在自定义变量名中使用`$`的地方，表示该变量是一个DOM实例。
  - `update()`，所在组件的 VNode 更新时被调用。

**Comment by 17373432** [comment]
陈驰-进度汇报
看完了基础部分的教学视频，了解了个大概，很多细节方面还不理解。

**Comment by linfeng-du** [comment]
杜林峰-进度汇报
#### 已完成
- 基础部分视频学习，了解了Vue对HTML对象的修饰作用。粗略了解语法。
- 总体认识：JavaScript将HTML对象作为整体操作，而Vue.js通过为其赋予修饰操作，更为灵活。

#### 下一步
结合源代码了解语法细节。

#### 疑问
是否在Vue.js框架下，所有JavaScript代码都应该是“Vue”的，二者不应该混用？抑或二者从两个方面共同控制HTML对象？

**Comment by Jiyuan-Yang** [comment]
任务完成。
