### ISSUE TITLE
Bug：团队事件说明打不开

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#20]
团队事件创建时需要有类似写代码一样的部分，但是这里说明打不开。

**Comment by Kennnnnnji** [comment]
## 问题更新
说明链接为：https://gist.github.com/luocaodan/cf175e433db58e0b150337ddad4c393a
打不开的原因属于网络环境问题

**Comment by Kennnnnnji** [comment]
## 解决方案
更改链接为：https://note.youdao.com/ynoteshare1/index.html?id=181dcd24c2add9473d0bc145e7ddeafa&type=note
使得国内网络环境也能打开

**Comment by Kennnnnnji** [comment]
## 代码 Change Log
### Commits
[fix bug: cannot open team events code illustration](https://github.com/Jiyuan-Yang/teach/commit/db113e1b7c10c03510ddc0b6f50443f91c1a5a4d)
[fix bug: cannot open team events code illustration V2](https://github.com/Jiyuan-Yang/teach/commit/65c16930c10d1c5c0ba2507c970e302a60b55f9f)

### 涉及文件
```
	modified:   app/javascript/packs/edit_team_event.js
	modified:   app/javascript/packs/new_team_event.js
	modified:   app/views/team_events/new.html.haml
```

**Comment by Kennnnnnji** [comment]
Finished.
