### ISSUE TITLE
Bug：团队项目列表一直是空的

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#21]
团队项目列表界面意义不明，没有创建按钮。

**Comment by Kennnnnnji** [comment]
## 问题更新
经过查阅代码，实际上这里限制只有学生视图能够创建团队项目
![image](https://user-images.githubusercontent.com/34367558/79300784-5038d300-7f1a-11ea-9a05-b506da82e649.png)

**Comment by Kennnnnnji** [comment]
## 代码更新
### Commit 
[create team proj -FrontEnd, and find bugs](https://github.com/Jiyuan-Yang/teach/commit/487f0c53d53987be7668b39203651442d89269ec)
### 描述
将创建团队项目接口转移至教师视图。

**Comment by Kennnnnnji** [comment]
发现创建团队项目有bug，已另建issue
