### ISSUE TITLE
Bug：新建的时候甚至可以选两个标签，又是todo又是doing

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#31]
新建时可以同时选择两个标签，最终结果是doing，查看的标签列依旧是空的，位置也默认在了todo。

**Comment by 804035184** [comment]
发现产生这个现象的原因应该为app/service/issue_service.rb中的add_state函数。这个函数逻辑是判断是否有todo 和doing标签，并使用或逻辑进行判断，doing在前。
同时对于state与label产生了疑问。
在gitlab中，issue有open和closed状态，对于open的状态的issue，可以加标签todo和doing。在本平台上，状态有todo，doing和closed，与gitlab上不符，就在这里的操作出现了一些问题。
在本平台上，新建issue的时候可以选择标签，其中有todo和doing，建立之后的issue的状态和新建时选择的标签一致，但新建的issue的标签项却为空。
感觉在本平台上 label与state应该是一个东西，但学长写的时候有时侯一致有时候不一致，逻辑比较混乱。

**Comment by 17373432** [comment]
目前问题为新建可以选择多个标签，当选了todo和doing时，新的问题的标签是doing但会被加入todo一栏，相应的权重和计数也会加到todo一栏，刷新之后该问题加到了doing一栏，权重和计数加在了doing一栏。

**Comment by 17373432** [comment]
学长代码中有初始化labels，具体位置在`app/controllers/system_controller.rb`中的`add_default_labels`，但是这个函数好像没被调用，目前还不知道具体原因。
