### ISSUE TITLE
完善组：冲刺部分的完善

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#33]
- 点击新建冲刺会选择项目名称，但没有区分班级，不同班级中的相同名字的项目无法区分。
- 查看建立的冲刺中有看板选项，意义不明。我（dzx）理解是对应的项目的看板，但却跳转到了一个意义不明的空的看板。
- 冲刺没有显示是哪个班级哪个项目，不同班级项目的同名冲刺无法区分，并且冲刺没有跳转到gitlab的选项，在平台中永远无法区分
- 冲刺详情里面的燃尽图看起来是因为拉取到了空的看板所以是空的
- 冲刺建立的时候若没有设置起始和截至时间，在查看冲刺详情的时候会让添加开始日期和截止日期，但是每次点击开始日期和截止日期配置都会出现服务器错误的报错，并且也没有确定修改的选项
- 冲刺有close和reopen按钮，但是意义不明

**Comment by Kennnnnnji** [comment]
## 代码更新
### Commit
[add class names for creating milestones](https://github.com/Jiyuan-Yang/teach/commit/79e92c633b307e93eb1db94345c147025129ec65)
### 描述
给新建冲刺选择项目名称时，添加班级名字说明
### 涉及文件
```
	modified:   app/controllers/classrooms_controller.rb
	modified:   app/helpers/application_helper.rb
	modified:   app/javascript/src/shared/components/navbar.vue
```

**Comment by Kennnnnnji** [comment]
## 代码更新
### Commit
[add proj id description in milestones](https://github.com/Jiyuan-Yang/teach/commit/d8eb430103f6fc0a23a1f87418132905999ba9d0)
[add classroom & proj description for milestones](https://github.com/Jiyuan-Yang/teach/commit/25b81c5eb1dccf6ab109984b5e0b0f88cd79cb37)
### 描述
冲刺详情中添加了对应班级和项目的描述
### 涉及文件
```
app/javascript/src/burndown/components/detail_sprint.vue
```

**Comment by Kennnnnnji** [comment]
## 代码更新
### 描述
修复了冲刺详情页的一个bug
### Commit
[ix bug of detail sprint](https://github.com/Jiyuan-Yang/teach/commit/f92503195130292e224fba7ac4cf0a6509c199e6)
### 设计文件
```
modified:   app/javascript/src/burndown/components/detail_sprint.vue
```
