### ISSUE TITLE
Bug：班级博客与Scrum新建

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#35]
在班级博客中点击新建博客，创建完后一直加载中转圈，新建Daily Scrum也是一样的情况。

**Comment by 804035184** [comment]
在进入或新建博客后，
RestClient::Unauthorized (401 Unauthorized):
```
  
lib/http.rb:6:in `get'
lib/http.rb:43:in `json_get'
lib/gitlab_api.rb:8:in `admin_api_get'
app/controllers/blogs_controller.rb:29:in `block (3 levels) in index'
app/controllers/blogs_controller.rb:25:in `block (2 levels) in index'
app/controllers/blogs_controller.rb:5:in `index'
```
rails server有如上述信息，看起来是身份验证的问题，正在进一步探究。

**Comment by 804035184** [comment]
上述测评是在学生和教师使用同一个账号的结果
在我使用只是学生的账户打开班级博客界面时，在rails中也出现了相同的现象，
`RestClient::Unauthorized (401 Unauthorized):
  
lib/http.rb:6:in `get'
lib/http.rb:43:in `json_get'
lib/gitlab_api.rb:8:in `admin_api_get'
app/controllers/blogs_controller.rb:29:in `block (3 levels) in index'
app/controllers/blogs_controller.rb:25:in `block (2 levels) in index'
app/controllers/blogs_controller.rb:5:in `index'
`
这个未验证的信息看起来扑朔迷离
同时还发现了被拉进班级的学生在新建博客的时候找不到班级和项目的BUG，我写在了新的issue中

**Comment by 804035184** [comment]
博客功能是基于gitlab的Snippets（代码片段实现的），代码片段在每个仓库左侧菜单栏倒数第二个。
目前发现，创建博客确实在gitlab中成功建立了snippets。
从前端出发，在app/javascript/packs/blogs.js的mounted中建立了一个blogsdService对象，然后调用其updateBlogs方法，updateBlogs方法调用blogsService的all方法。
blogsService方法在app/javascript/src/blogs/service/blogs_service.js中定义，使用axios.get读取数据。
经测试，发现于此axios.get方法出现问题，axios.get在浏览器的控制台给出了Request failed with status code 500的错误。
推测问题可能为以下几种
参数传入错误，axios.get方法传入的参数有blogsEndpoint和{params: params}，其中，blogsEndpoint在newblog方法中也使用了，可以认为无错误，故可能出在params，params是all方法传入的参数，来自于调用它的updateBlogs(app/javascript/packs/blogs.js)，updateBlogs的params来自于mounted传入的this.searchParams。目前还不知道这个参数的来源以及意义。
尝试去寻找创建博客的方法，发现和项目看板等不太一样，是在packs/new_blog.js中定义。new_blog.js中有createBlog方法，这个方法调用了app/javascript/src/blogs/service/blogs_service.js中的newBlog方法，但在new_blog.js的mounted方法里面并没有调用这个createBlog方法
代码如下：
`mounted() {
      const $app = this.$el;
      this.type = $app.dataset.blogsType;
      this.blogsService = new BlogsService({
        blogsEndpoint: $app.dataset.blogsEndpoint
      });
      const navbar = document.getElementById('navbar');
      this.issuesService = new IssuesService({
        issuesEndpoint: navbar.dataset.issuesEndpoint
      });
      this.blog = new Blog(this.type);
      const $navbar = document.getElementById('navbar');
      let projects = JSON.parse($navbar.dataset.projects);
      for (let project of projects) {
        if (this.type === 'blog') {
          this.containers.push({
            id: project.id,
            name: project.name,
          });
        } else {
          let milestones = project.milestones;
          for (let milestone of milestones) {
            this.containers.push({
              id: `${project.id}-${milestone.id}`,
              name: milestone.title
            });
          }
        }
      }
    }`
看起来是找到这个元素的ID，然后通过JSON.parse得到projects然后遍历这个projects调用this.containers.push({
            id: project.id,
            name: project.name,
          })
这样的一个方法去传数据。

**Comment by 804035184** [comment]
分配仓库后得到权限，没有其他问题
