### ISSUE TITLE
预习任务-后端：Ruby on Rails

### ISSUE THREAD

**Issue by Kennnnnnji** [Jiyuan-Yang/teach#4]
[官方教程](https://guides.rubyonrails.org/)
[如何快速学习 Ruby on Rails？](https://www.zhihu.com/question/19552402)
掌握web基础，学习Rails框架，熟悉相应API。
请大家及时汇报学习情况，尽快完成。

**Comment by Kennnnnnji** [comment]
# 进度汇报-0408
## 完成学习以下部分：
- [x] 完成第一次RoR部署
- [x] 搭建一个toy-app
- [x] 编写基本静态的页面
- [x] 学习基本Ruby语法
## 正在学习：
- [x] 完善布局

**Comment by 804035184** [comment]
进度汇报：
完成以下部分：
基本ruby语法基本学习完成
成功配置RoR
正在学习：
搭建RoR项目

**Comment by Leomiku** [comment]
进度汇报：
完成以下部分：
ruby基础学习基本完成
配置RoR开发环境
第一个RoR应用
正在学习：
搭建玩具项目

**Comment by Jiyuan-Yang** [comment]
任务完成。
