### ISSUE TITLE
BUG：学生拉取班级信息

### ISSUE THREAD

**Issue by 804035184** [Jiyuan-Yang/teach#41]
被拉进班级学生在项目看板、冲刺、问题等界面都找不到所在的班级及项目
在新建博客的时候也找不到所在的班级

**Comment by Kennnnnnji** [comment]
## 问题补充
root账户进行学生登录能看到对应内容，但是学生账户登录无法看到内容
![JpEJOK.png](https://s1.ax1x.com/2020/04/14/JpEJOK.png)

**Comment by 17373432** [comment]
在`app/helper/application_helper.rb`文件中的`project_data`中只有将`min_access_level`设置成10才能显示出项目信息，具体原理还没弄清楚。

**Comment by 17373432** [comment]
这里的`min_access_level`是最小访问权限，由于我新的学生用户身份为Guest，权限为10，所以之前`min_access_level=30`时无法访问，`bug`原因应该是在加入班级和拉学生进班时权限没有设置为`Developer`
