### ISSUE TITLE
BUG：gitlab中多页面问题

### ISSUE THREAD

**Issue by 804035184** [Jiyuan-Yang/teach#45]

**Comment by 804035184** [comment]
目前的情况是，如果issues在gitlab中有多页，刚打开界面的时候只会展示gitlab中第一页包含的数据。只有当某一列的数据超出一页，使用鼠标滑轮进行翻页时才会继续拉取数据。
由此和会产生一个严重的bug
即，非若gitlab第一页的数据在todo doing或closed这三项中需要显示，不滑动鼠标滑轮无法显现出来，明显的复现方式：新建超过20个issue，比如21个，将gitlab中的第21个issue（也就是你第一个建立的issue）的标签改称doing，其余都是todo，这样刚进入时doing列没有issue显示，只有当滑动todo列才会显现。

**Comment by 804035184** [comment]
由此还有一个更加严重的bug
新建大量的issues，超过20条，然后将gitlab中第一页的20条issues在项目看板中均匀分布一下，使得在todo doing closed三列都不出现分页，那么第一页以外的issues将没有途径去显示。

**Comment by 17373432** [comment]
现在已经能将gitlab所有页面的issue都显示出来
