### ISSUE TITLE
BUG：创建团队项目出现400 BadRequest

### ISSUE THREAD

**Issue by Kennnnnnji** [Jiyuan-Yang/teach#48]
导致进入rescue并输出错误信息

**Comment by 804035184** [comment]
创建团队项目，输入名称和描述后出现“BadRequest, 可能名称或地址包含非法字符”的提示，但gitlab上却创建成功

**Comment by Kennnnnnji** [comment]
## bug 追踪
尝试在`/app/controllers/team_projects_controller.rb`的`create`方法添加如下代码：
```ruby
 team_proj_record = classroom.team_projects.new
 team_proj_record.gitlab_id = @team_project['id']
 team_proj_record.test_type = @team_project[:test_type]
 team_proj_record.save
```
仍然报错。

**Comment by 804035184** [comment]
我的情况是创建团队项目出现错误提示，但能正常创建，并且刷新后也没有其他问题，会在平台上正常现实
目前定位到teamproject_controller中的create函数，在调用add_project_master_as_owner的时候出现错误，进而定位到这个文件中的add_project_master_as_owner方法中的admin_api_post出现错误
猜测是想把owner降级为maintainer遭到gitlab拒绝
