### ISSUE TITLE
bug:教师端登陆界面

### ISSUE THREAD

**Issue by 804035184** [Jiyuan-Yang/teach#50]
教师端登陆后出现403Forbidden You are not authorized的界面
刷新后进入正常的班级界面

**Comment by 804035184** [comment]
当我在gitlab中删除了所有的班级后，再清掉cookie登教师端的时候，除了 刚进去的403外，刷新后就直接报

RestClient::NotFound in ClassroomsController#index
404 Not Found

**Comment by 804035184** [comment]
当我在gitlab中没有班级
重新删掉又clone一个项目的时候
第一次进入教师端又没有出现这个403
比较神奇

**Comment by Kennnnnnji** [comment]
问题是否能够复现？

**Comment by Kennnnnnji** [comment]
老版本代码没有出现这一bug，问题出处还需要定位

**Comment by 804035184** [comment]
这个403界面是当学生身分的用户去登陆教师端出现的，不作为bug，但学生在刷新后可以修改班级，权限需要进一步完善
