### ISSUE TITLE
BUG：编辑班级

### ISSUE THREAD

**Issue by 804035184** [Jiyuan-Yang/teach#51]
我建立了class1 class2 class3三个班级
在对class1进行修改时，名字改称class2会正常报错
但是！！！
我对class2，class3进行修改时，如果名字改为class1并不会报错，并且会改变原本class1的信息！！！

**Comment by 804035184** [comment]
![2020-04-18 21-04-56 的屏幕截图](https://user-images.githubusercontent.com/47777277/79638514-4d5b0e00-81b8-11ea-8733-04c6cc0038c4.png)
![2020-04-18 21-05-51 的屏幕截图](https://user-images.githubusercontent.com/47777277/79638528-695eaf80-81b8-11ea-88ec-4547f3df3cc0.png)
![2020-04-18 21-05-54 的屏幕截图](https://user-images.githubusercontent.com/47777277/79638531-6bc10980-81b8-11ea-8586-5915cd71e0af.png)

**Comment by 804035184** [comment]
![2020-04-18 21-04-56 的屏幕截图](https://user-images.githubusercontent.com/47777277/79638542-7aa7bc00-81b8-11ea-938d-5897e921bbd2.png)

**Comment by 804035184** [comment]
![Uploading 2020-04-18 21-04-56 的屏幕截图.png…]()

**Comment by 804035184** [comment]
[https://github.com/804035184/teach/blob/804035184-patch-1/2020-04-18%2021-04-56%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png](url)

**Comment by 804035184** [comment]
https://github.com/804035184/teach/blob/804035184-patch-1/2020-04-18%2021-04-56%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by Kennnnnnji** [comment]
已修复 

> https://github.com/Jiyuan-Yang/teach/issues/63
