### ISSUE TITLE
BUG：创建项目

### ISSUE THREAD

**Issue by 804035184** [Jiyuan-Yang/teach#53]
创建个人项目时提示非法或已被占用，但gitlab成功创建，刷新后出现
NoMethodError in Classrooms#show

Showing /home/dzx/teach/app/views/classrooms/show.html.haml where line #69 raised:

undefined method `id' for nil:NilClass
的报错

**Comment by 804035184** [comment]
结对项目也存在相同的问题
只要创建过个人结对项目，进入班级界面，就会报这个错
在gitlab中把创建成功的project删除就不会出现这个报错信息

**Comment by 804035184** [comment]
但在我将gitlab清空
并且删掉重新clone时，个人和结对项目就不会出现这个问题
可能是由于在部署平台之前gitlab上面已经存在信息的问题

**Comment by Jiyuan-Yang** [comment]
无法复现此问题，刚刚测试过，创建公共项目没有此问题，批量生成仓库在创建过程中会有中间状态，这个我会处理，创建完毕后可以正常访问，对于重复创建缺少审核，但是这个现象是gitlab会卡住，显示500或404，这个我也会尽快处理。创建个人项目中的单个学生目前有bug无法使用，我也抓紧去处理。请检查一下是否因为重新删除后clone导致gitlab与平台数据库不一致，这边并没有因为gitlab创建了项目导致班级打不开的情况，请找其他同学确认一下这是不是一个bug。

**Comment by 804035184** [comment]
身份为学生的用户在登陆教师端时，会出现这个问题
创建个人项目时提示非法或已被占用，但gitlab成功创建，刷新后出现
NoMethodError in Classrooms#show
的报错
