### ISSUE TITLE
BUG:issue close，reopen的刷新问题

### ISSUE THREAD

**Issue by 804035184** [Jiyuan-Yang/teach#59]
issue在close后只会将标签变化，并不会立即移到closed行，刷新后才会正常
reopen类似

**Comment by 804035184** [comment]
issue的修改都存在这上述类似的更新问题。
比较明显的体现在对权重的修改上。修改issue的权重，在计数一栏并不会发生变化，此时若移动issue改变state，权重会以错误的值继续变化。刷新后恢复正常，应该是更新时没有同步到本地数据库的原因。

**Comment by 17373432** [comment]
已修复
