### ISSUE TITLE
BUG:新建问题时创建失败

### ISSUE THREAD

**Issue by 804035184** [Jiyuan-Yang/teach#62]
在新建问题时，有权重但未选择标签会出现创建问题失败的错误提示，但刷新界面后会显示创建成功
并且这个问题我在尝试复现时发现很玄学，有的时候不会
目前我找到的比较稳定的一种复现方式是，只输入名字，权重，经办人，点击创建

**Comment by 804035184** [comment]
在设置了权重，优先级，经办人，标签，截止日期时也能复现出这个bug
并且刷新后创建出来的issue 优先级和权重为空

**Comment by 17373432** [comment]
新建问题如果不选择标签，默认的标签是`Open`，会加到`todo`列，刷新后消失。

**Comment by 804035184** [comment]
复现此bug可以尝试只设置权重不断创建，大概十次左右会出现（非洲人可能会连续遇到
提示错误后创建出来的issue丢失了权重信息

**Comment by 804035184** [comment]
可能是gitlab的响应问题
