### ISSUE TITLE
批量添加成员

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#74]
要求用户上传文件/在一个textarea里复制所有学号信息（具体格式实现时可以自定），根据信息生成GitLab账户。

**Comment by 804035184** [comment]
完成初步的批量添加gitlab用户功能
在教师界面最上面有新建用户按钮
进入后按照规则输入信息
点击创建即可
接下来需要做的
还没有添加到数据库中赋予学生身分，目前的情况是无身份，在添加学生 和添加教师助教里都能 看见，接下来增加数据库操作
接下来增加合法性检查，除了本身的合法性，还要从已有的User中查找重复
这个查重在前端还是后端加还未决定 
对应Commit: f77f6ad

**Comment by 804035184** [comment]
增加了对输入信息的正则匹配检测
增加了与已有的gitlab账号查询的功能，并给出已存在的重复的账号
增加了将 新建的账号加入本地数据库并赋予学生身分的功能
发现 本地数据库中为student，但在班级的添加教师 助教中依旧会出现该成员的bug，疑似祖传bug，另开issue
还需要进一步完善的
细化正则匹配规则，参照gitlab的标准对账号，密码等进行标准细化
目前需要保证所有的账号都在本地数据库有记录
（可能还可以美化
（可能还可以增加从文件读取的功能
对应Commit: df30211
