### ISSUE TITLE
班级中批量创建结对和团队项目

### ISSUE THREAD

**Issue by Jiyuan-Yang** [Jiyuan-Yang/teach#75]

**Comment by Kennnnnnji** [comment]
## 已完成
https://github.com/Jiyuan-Yang/teach/commit/aabac624fef253476cba27fb4610dc64ac2d606a
https://github.com/Jiyuan-Yang/teach/commit/ee11e8c1eb0cf309417d64b755149c24ac906cc3
https://github.com/Jiyuan-Yang/teach/commit/e5f9b5c39c9f165109404fdd18bc99aab0ddb9cf
https://github.com/Jiyuan-Yang/teach/commit/522bf645fccc2d300e305d4179dfc62f9c15b960
https://github.com/Jiyuan-Yang/teach/commit/8d81842e9baec2bcbfa3a485a521ae1b1b2bb066
https://github.com/Jiyuan-Yang/teach/commit/dd45c3620128bfa06c595a70e0696a66596624a3
https://github.com/Jiyuan-Yang/teach/commit/c96e0b26482c0ac2b61a8a3a85f72f862e015d0d
https://github.com/Jiyuan-Yang/teach/commit/857706d1b110601e75da0c5f154496e887979faa
