### ISSUE TITLE
熟悉代码-后端

### ISSUE THREAD

**Issue by c2170** [Jiyuan-Yang/teach#9]

**Comment by Kennnnnnji** [comment]
### 在`app/controllers/`目录下的controller文件的review：

| 文件                             | 功能                                         | 备注 |
| -------------------------------- | -------------------------------------------- | ---- |
| application_controller.rb        |                                              |      |
| auto_test_projects_controller.rb | 控制自动测试，反馈、触发等                   |      |
| blogs_controller.rb              | 博客的创建、删除等                           |      |
| boards_controller.rb             | 看板（boards#index）                         |      |
| burndown_controller.rb           | 燃尽（burndown#index）                       |      |
| classrooms_controller.rb         | 班级管理                                     |      |
| comments_controller.rb           | 评论管理，创建、更新等                       |      |
| insight_controller.rb            | 实现insight功能                              |      |
| issues_controller.rb             | issue的控制，创建、更新                      |      |
| pages_controller.rb              | 页面重定向，登录、学生→issue、教师→classroom |      |
| projects_controller.rb           | 管理项目，包括标签、成员等                   |      |
| report_controller.rb             | 管理报告，实现测试打分等功能                 |      |
| sessions_controller.rb           | 管理会话，登录重定向、用户创建等             |      |
| sprints_controller.rb            | sprints服务                                  |      |
| system_controller.rb             | 提供系统服务，如获取group的id，添加默认label |      |
| team_events_controller.rb        | 管理团队活动，如events的创建、展示           |      |
| team_projects_controller.rb      | 管理团队项目                                 |      |
| uploads_controller.rb            | 实现上传功能                                 |      |
| users_controller.rb              | 管理用户类，创建和删除                       |      |
| webhook_controller.rb            | 控制webhook                                  |      |

**Comment by Jiyuan-Yang** [comment]
任务完成。
